version: "3.7"

services:
#  volumes:
#      - /home/supprt/TEST_files/database:/app

  database:
    image: mysql:latest

#    container_name: mysql_fight
    volumes:
    - ./db_fight/databases:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fight_db
      MYSQL_USER: fight
      MYSQL_PASSWORD: fight
#    ports:
#      - "3306:3306"
#    network_mode: host

  app_node:
    build: ./app_fight
#    container_name: app-node_fight
    depends_on:
      - database
#    environment:
#      DB_CLIENT: "mysql"
#      DB_HOST: "database"
#      DB_PORT: "3306"
#      DB_DATABASE: fight_db
#      DB_USER: fight
#      DB_PASSWORD: fight
