# This is comment

name: My-GitHubActions
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: install ssh keys
          # check this thread to understand why its needed:
          # <https://stackoverflow.com/a/70447517>
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.SSH_HOST }} > ~/.ssh/known_hosts
        
      - name: copy docker compose config
        run: scp -r ./* ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:nodeapp

      - name: docker compose up -d
        run: ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "docker compose up -d"



        


